CREATE TABLE [dbo].[Person]
(
	[Id_PERSON] INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] VARCHAR (100) NOT NULL,
	[LAST_NAME] VARCHAR (100) NOT NULL,
	[BIRTHDATE] DATETIME NOT NULL ,
	[NUMBER_TEL] INT,
	[STREET] VARCHAR (100) NOT NULL ,
	[NUMBER] INT NOT NULL ,
	[CDE_POSTAL] INT , 
	[CITY] VARCHAR (100) NOT NULL ,
	[COUNTRY] VARCHAR (100) NOT NULL ,
	[ADRESS_MAIL] VARCHAR (250) NOT NULL UNIQUE
)
